FROM php:8.2-apache

# Installer dépendances PostgreSQL
RUN apt-get update && apt-get install -y libpq-dev

# Installer extensions PHP
RUN docker-php-ext-install pdo pdo_pgsql

# Activer mod_rewrite
RUN a2enmod rewrite

# Adapter Apache au PORT Railway
RUN sed -i 's/80/${PORT}/g' /etc/apache2/ports.conf /etc/apache2/sites-available/000-default.conf

# Copier projet
COPY . /var/www/html/

RUN chown -R www-data:www-data /var/www/html

EXPOSE 80